### ISSUE TITLE
添加词组查询

### ISSUE THREAD

**Issue by TomCC7** [LighghtEeloo/charcoal#1]
![image](https://user-images.githubusercontent.com/55869557/174332508-cc4b21ae-cf4b-4fd0-a62f-cf45d0124c3f.png)
目前可以使用双引号将argument括起来 不过如果不用的话肯定更好 😊

**Comment by LighghtEeloo** [comment]
有道理 这个可以安排

**Comment by LighghtEeloo** [comment]
见 f258a71d9c14f643d6ad556ff67ae3e8c62290e8
