### ISSUE TITLE
中文搜索的输出看起来很奇怪

### ISSUE THREAD

**Issue by TomCC7** [LighghtEeloo/charcoal#2]
![image](https://user-images.githubusercontent.com/55869557/174332717-2196986f-fd6d-4bdd-8f98-19b7b29dc798.png)

**Comment by LighghtEeloo** [comment]
这个项目本来就是为了英文搜索而建立的…不过这个有条件的话可以适配

**Comment by TomCC7** [comment]
aba 中转英不是也挺常用 🤪

**Comment by LighghtEeloo** [comment]
哦……有道理啊

我之后去加一个模式的概念试试

**Comment by TomCC7** [comment]
wudao咋做的

**Comment by LighghtEeloo** [comment]
非常的简单：

<img width="606" alt="Screen Shot 2022-06-17 at 15 11 22" src="https://user-images.githubusercontent.com/24841828/174387893-c98890fd-0fdf-4c66-bdc8-45afd2dafe14.png">

**Comment by TomCC7** [comment]
🌿

**Comment by LighghtEeloo** [comment]
Applied `whatlang` crate and fixed in ad3fa846.

**Comment by TomCC7** [comment]
Hmm 感觉颜色还是怪怪的
![image](https://user-images.githubusercontent.com/55869557/174481492-10963d58-9f3e-4097-879a-fd6714e44620.png)

**Comment by Gorgeous-Patrick** [comment]
> 非常的简单：
> 
> <img alt="Screen Shot 2022-06-17 at 15 11 22" width="606" src="https://user-images.githubusercontent.com/24841828/174387893-c98890fd-0fdf-4c66-bdc8-45afd2dafe14.png">

我：姜教我dafny
姜：非常的简单
