### ISSUE TITLE
示例句子单词间没有空格

### ISSUE THREAD

**Issue by lingllqs** [LighghtEeloo/charcoal#7]
![图片](https://github.com/LighghtEeloo/charcoal/assets/77040720/16cbbcfb-d63e-4efa-8a23-0e52195092e7)

**Comment by LighghtEeloo** [comment]
Thank you for bring it up. The issue is fixed in 2db50db23ca6d601e91da6c24429c5776930b72d. The problem was I messed up the logic for adding whitespace or not for eastern and western tokens. I've released the updated version on cargo and aur.

Closing as resovled.
